/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'barringtonhenry' at '3/13/16 1:42 AM' with Gradle 2.11
 *
 * @author barringtonhenry, @date 3/13/16 1:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
